---
abstract: 'DBIx::Class interface for Dancer applications'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
  - 'Naveed Massjouni <ironcamel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-DBIC
requires:
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0.07002
  Dancer: 0
version: 0.1502
