---
abstract: 'DBIx::Class interface for Dancer applications'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
  - 'Naveed Massjouni <naveed.massjouni@rackspace.com>'
  - 'Alexis Sukrieh <sukria@sukria.net>'
  - 'Franck Cuny <franck@lumberjaph.net>'
  - 'David Precious <davidp@preshweb.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-DBIC
requires:
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0.07002
  Dancer: 0
resources:
  bugtracker: https://github.com/ironcamel/Dancer-Plugin-DBIC/issues
  repository: git://github.com/ironcamel/Dancer-Plugin-DBIC.git
version: 0.1505
